//! ISO 3166-1 alpha-3 → alpha-2, for the country class that lets tools such
//! as Maphue colour maps by country (geoBoundaries only carries alpha-3).
//! Derived from Natural Earth's `ISO_A3_EH`/`ISO_A2_EH` (public domain), plus
//! Kosovo's user-assigned `XKX`/`XK`.

const ALPHA3_TO_ALPHA2: [(&str, &str); 239] = [
    ("ABW", "AW"),
    ("AFG", "AF"),
    ("AGO", "AO"),
    ("AIA", "AI"),
    ("ALA", "AX"),
    ("ALB", "AL"),
    ("AND", "AD"),
    ("ARE", "AE"),
    ("ARG", "AR"),
    ("ARM", "AM"),
    ("ASM", "AS"),
    ("ATA", "AQ"),
    ("ATF", "TF"),
    ("ATG", "AG"),
    ("AUS", "AU"),
    ("AUT", "AT"),
    ("AZE", "AZ"),
    ("BDI", "BI"),
    ("BEL", "BE"),
    ("BEN", "BJ"),
    ("BFA", "BF"),
    ("BGD", "BD"),
    ("BGR", "BG"),
    ("BHR", "BH"),
    ("BHS", "BS"),
    ("BIH", "BA"),
    ("BLM", "BL"),
    ("BLR", "BY"),
    ("BLZ", "BZ"),
    ("BMU", "BM"),
    ("BOL", "BO"),
    ("BRA", "BR"),
    ("BRB", "BB"),
    ("BRN", "BN"),
    ("BTN", "BT"),
    ("BWA", "BW"),
    ("CAF", "CF"),
    ("CAN", "CA"),
    ("CHE", "CH"),
    ("CHL", "CL"),
    ("CHN", "CN"),
    ("CIV", "CI"),
    ("CMR", "CM"),
    ("COD", "CD"),
    ("COG", "CG"),
    ("COK", "CK"),
    ("COL", "CO"),
    ("COM", "KM"),
    ("CPV", "CV"),
    ("CRI", "CR"),
    ("CUB", "CU"),
    ("CUW", "CW"),
    ("CYM", "KY"),
    ("CYP", "CY"),
    ("CZE", "CZ"),
    ("DEU", "DE"),
    ("DJI", "DJ"),
    ("DMA", "DM"),
    ("DNK", "DK"),
    ("DOM", "DO"),
    ("DZA", "DZ"),
    ("ECU", "EC"),
    ("EGY", "EG"),
    ("ERI", "ER"),
    ("ESH", "EH"),
    ("ESP", "ES"),
    ("EST", "EE"),
    ("ETH", "ET"),
    ("FIN", "FI"),
    ("FJI", "FJ"),
    ("FLK", "FK"),
    ("FRA", "FR"),
    ("FRO", "FO"),
    ("FSM", "FM"),
    ("GAB", "GA"),
    ("GBR", "GB"),
    ("GEO", "GE"),
    ("GGY", "GG"),
    ("GHA", "GH"),
    ("GIB", "GI"),
    ("GIN", "GN"),
    ("GMB", "GM"),
    ("GNB", "GW"),
    ("GNQ", "GQ"),
    ("GRC", "GR"),
    ("GRD", "GD"),
    ("GRL", "GL"),
    ("GTM", "GT"),
    ("GUM", "GU"),
    ("GUY", "GY"),
    ("HKG", "HK"),
    ("HMD", "HM"),
    ("HND", "HN"),
    ("HRV", "HR"),
    ("HTI", "HT"),
    ("HUN", "HU"),
    ("IDN", "ID"),
    ("IMN", "IM"),
    ("IND", "IN"),
    ("IOT", "IO"),
    ("IRL", "IE"),
    ("IRN", "IR"),
    ("IRQ", "IQ"),
    ("ISL", "IS"),
    ("ISR", "IL"),
    ("ITA", "IT"),
    ("JAM", "JM"),
    ("JEY", "JE"),
    ("JOR", "JO"),
    ("JPN", "JP"),
    ("KAZ", "KZ"),
    ("KEN", "KE"),
    ("KGZ", "KG"),
    ("KHM", "KH"),
    ("KIR", "KI"),
    ("KNA", "KN"),
    ("KOR", "KR"),
    ("KWT", "KW"),
    ("LAO", "LA"),
    ("LBN", "LB"),
    ("LBR", "LR"),
    ("LBY", "LY"),
    ("LCA", "LC"),
    ("LIE", "LI"),
    ("LKA", "LK"),
    ("LSO", "LS"),
    ("LTU", "LT"),
    ("LUX", "LU"),
    ("LVA", "LV"),
    ("MAC", "MO"),
    ("MAF", "MF"),
    ("MAR", "MA"),
    ("MCO", "MC"),
    ("MDA", "MD"),
    ("MDG", "MG"),
    ("MDV", "MV"),
    ("MEX", "MX"),
    ("MHL", "MH"),
    ("MKD", "MK"),
    ("MLI", "ML"),
    ("MLT", "MT"),
    ("MMR", "MM"),
    ("MNE", "ME"),
    ("MNG", "MN"),
    ("MNP", "MP"),
    ("MOZ", "MZ"),
    ("MRT", "MR"),
    ("MSR", "MS"),
    ("MUS", "MU"),
    ("MWI", "MW"),
    ("MYS", "MY"),
    ("NAM", "NA"),
    ("NCL", "NC"),
    ("NER", "NE"),
    ("NFK", "NF"),
    ("NGA", "NG"),
    ("NIC", "NI"),
    ("NIU", "NU"),
    ("NLD", "NL"),
    ("NOR", "NO"),
    ("NPL", "NP"),
    ("NRU", "NR"),
    ("NZL", "NZ"),
    ("OMN", "OM"),
    ("PAK", "PK"),
    ("PAN", "PA"),
    ("PCN", "PN"),
    ("PER", "PE"),
    ("PHL", "PH"),
    ("PLW", "PW"),
    ("PNG", "PG"),
    ("POL", "PL"),
    ("PRI", "PR"),
    ("PRK", "KP"),
    ("PRT", "PT"),
    ("PRY", "PY"),
    ("PSE", "PS"),
    ("PYF", "PF"),
    ("QAT", "QA"),
    ("ROU", "RO"),
    ("RUS", "RU"),
    ("RWA", "RW"),
    ("SAU", "SA"),
    ("SDN", "SD"),
    ("SEN", "SN"),
    ("SGP", "SG"),
    ("SGS", "GS"),
    ("SHN", "SH"),
    ("SLB", "SB"),
    ("SLE", "SL"),
    ("SLV", "SV"),
    ("SMR", "SM"),
    ("SOM", "SO"),
    ("SPM", "PM"),
    ("SRB", "RS"),
    ("SSD", "SS"),
    ("STP", "ST"),
    ("SUR", "SR"),
    ("SVK", "SK"),
    ("SVN", "SI"),
    ("SWE", "SE"),
    ("SWZ", "SZ"),
    ("SXM", "SX"),
    ("SYC", "SC"),
    ("SYR", "SY"),
    ("TCA", "TC"),
    ("TCD", "TD"),
    ("TGO", "TG"),
    ("THA", "TH"),
    ("TJK", "TJ"),
    ("TKM", "TM"),
    ("TLS", "TL"),
    ("TON", "TO"),
    ("TTO", "TT"),
    ("TUN", "TN"),
    ("TUR", "TR"),
    ("TUV", "TV"),
    ("TWN", "TW"),
    ("TZA", "TZ"),
    ("UGA", "UG"),
    ("UKR", "UA"),
    ("UMI", "UM"),
    ("URY", "UY"),
    ("USA", "US"),
    ("UZB", "UZ"),
    ("VAT", "VA"),
    ("VCT", "VC"),
    ("VEN", "VE"),
    ("VGB", "VG"),
    ("VIR", "VI"),
    ("VNM", "VN"),
    ("VUT", "VU"),
    ("WLF", "WF"),
    ("WSM", "WS"),
    ("XKX", "XK"),
    ("YEM", "YE"),
    ("ZAF", "ZA"),
    ("ZMB", "ZM"),
    ("ZWE", "ZW"),
];

/// Normalises a country code to lowercase ISO 3166-1 alpha-2: alpha-2 codes
/// pass through, alpha-3 codes are looked up; anything else is `None`.
pub fn country_alpha2(code: &str) -> Option<String> {
    let code = code.trim().to_ascii_uppercase();
    match code.len() {
        2 if code.chars().all(|c| c.is_ascii_uppercase()) => Some(code.to_ascii_lowercase()),
        3 => ALPHA3_TO_ALPHA2
            .binary_search_by(|(a3, _)| (*a3).cmp(code.as_str()))
            .ok()
            .map(|i| ALPHA3_TO_ALPHA2[i].1.to_ascii_lowercase()),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalises_codes() {
        assert_eq!(country_alpha2("FRA").as_deref(), Some("fr"));
        assert_eq!(country_alpha2("nor").as_deref(), Some("no"));
        assert_eq!(country_alpha2("XKX").as_deref(), Some("xk"));
        assert_eq!(country_alpha2("US").as_deref(), Some("us"));
        assert_eq!(country_alpha2("-99"), None);
        assert_eq!(country_alpha2("ZZZ"), None);
    }

    #[test]
    fn table_is_sorted_for_binary_search() {
        assert!(ALPHA3_TO_ALPHA2.windows(2).all(|w| w[0].0 < w[1].0));
    }
}
